name: build-arm
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: read

concurrency:
  group: build-arm-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      arm: true
