name: build-x64
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: read

concurrency:
  group: build-x64-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
